### ISSUE TITLE
The Incredible Machine 2 black screen

### ISSUE THREAD

**Issue by andremedeiros** [flynnsbit/Top300_updates#79]
After the new update, I can hear sound, but I don't get any image when I start the game.

**Comment by flynnsbit** [comment]
Incredible Machines was always like that on the core.  You need the Trident VGA bios instead of the ET4000 and that fixes a set of games in the core.  What this means is you need to flip back and forth between the bios files on the core depending on the game.  You can use Seth's boot switcher script to make this easy.  it is here.  

https://github.com/sethgregory/ao486_boot_switcher

FYI,this is a core bug or video bug that I can't do anything about so this is the fix.

**Comment by jmej** [comment]
Thanks for mentioning this here - this script has helped out a bunch, it might be nice to throw this info on a readme somewhere. It's helpful to leave this issue open as long as this info is needed.

**Comment by andremedeiros** [comment]
Oh this is news. Thank you for replying. I'll close the issue and hope folks with the same issue can easily find it.

**Comment by jmej** [comment]
due to the nature of this project being all about automation, it feels like it's still an issue unless/until it's fixed through an automation script. possibly one that downloads sethgregory's script and runs it at game launch... if we leave the issue open possibly someone (maybe me if i can find time?) could work on that.

**Comment by andremedeiros** [comment]
I think you have to restart the core to load up the other bios. It's not swappable like that.

**Comment by flynnsbit** [comment]
> due to the nature of this project being all about automation, it feels like it's still an issue unless/until it's fixed through an automation script. possibly one that downloads sethgregory's script and runs it at game launch... if we leave the issue open possibly someone (maybe me if i can find time?) could work on that.

Not possible.  This is a bios swap for VGA and cannot be done from dos.  It has to be done from the mister side and then the core can start.  You can put a bug in the ao486 github if you want someone to look at the existing et4000 bios and see if it can be changed to make it similar to the Trident BIOS.
